name: Build the website
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: recursive
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: "Frontend: Install dependencies"
        working-directory: frontend
        run: pnpm i
      - name: "Site builder: Install dependencies"
        working-directory: builder
        run: npm i
      - name: Run markdownlint-cli2
        working-directory: builder
        run: npx markdownlint-cli2 ../content/*.md
      - name: "Frontend: Run ESLint"
        working-directory: frontend
        run: |
          pnpm exec eslint -c basic.eslint.config.js basic.eslint.config.js eslint.config.js
          pnpm exec eslint src
      - name: "Frontend: Type check"
        working-directory: frontend
        run: pnpm exec tsc --noEmit
      - name: "Site builder: Run ESLint"
        working-directory: builder
        run: |
          npx eslint -c basic.eslint.config.js basic.eslint.config.js eslint.config.js
          npx eslint src
      - name: "Site builder: Compile TypeScript"
        working-directory: builder
        run: npx tsc
      - name: Validate page JSONs
        working-directory: builder
        run: node dist/scripts/validate-page-jsons.js
      - name: Run Stylelint
        working-directory: builder
        run: npx stylelint '../content/**/*.css'
      - name: Build frontend
        working-directory: frontend
        run: scripts/build.sh
      - name: Build the website
        working-directory: builder
        run: node dist/makesite.js
        env:
          BASE_URL: https://mariogemoll.com
